version: "3.9"
services:
  app:
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
  db:
    restart: unless-stopped
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: cctv
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "--host=localhost",
          "--password=mysql",
          "--user=root",
        ]
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306
