version: "3.9"
services:
  app:
    build: .
    restart: unless-stopped
    environment:
      TZ: Europe/Prague
    depends_on:
      db:
        condition: service_healthy
  db:
    restart: unless-stopped
    image: linuxserver/mariadb
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Prague
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: cctv
      MYSQL_DATABASE: cctv
      MYSQL_PASSWORD: mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "--host=localhost",
          "--user=cctv",
          "--password=mysql",
        ]
      timeout: 20s
      retries: 10
    ports:
      - 3306
  prometheus:
    image: prom/prometheus
    volumes:
      - ./config:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    restart: always
