version: "3.9"
services:
  app:
    build: .
    command: ["yarn", "start"]
    restart: unless-stopped
    environment:
      TZ: Europe/Prague
    volumes:
      - ./config:/config
  db:
    restart: unless-stopped
    image: linuxserver/mariadb
    environment:
      TZ: Europe/Prague
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: cctv
      MYSQL_DATABASE: cctv
      MYSQL_PASSWORD: mysql
    ports:
      - 3306
  # prometheus:
  #   image: prom/prometheus
  #   volumes:
  #     - ./config:/etc/prometheus/
  #   command:
  #     - "--config.file=/etc/prometheus/prometheus.yml"
  #   ports:
  #     - 9090:9090
  #   restart: always
