version: "3.9"

x-cctv: &cctv
  build: .
  image: cctv
  restart: unless-stopped
  environment:
    TZ: Europe/Prague
  volumes:
    - ./config/dummy:/cctv/config
    - storage:/cctv/storage

services:
  <<: *workers
  server:
    <<: *cctv
    command: ["yarn", "start"]
    ports:
      - "3000:3000"
  sync:
    <<: *cctv
    command: ["yarn", "start:sync"]
  db:
    restart: unless-stopped
    image: linuxserver/mariadb
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Prague
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: cctv
      MYSQL_DATABASE: cctv
      MYSQL_PASSWORD: mysql
    ports:
      - 3306

volumes:
  storage:
