FROM node:14-alpine3.12
RUN apk update \
    && apk add --no-cache \
        ca-certificates \
        coreutils \
        curl \
        ffmpeg \
        g++ \
        git \
        gnupg \
        grep \
        less \
        libc6-compat \
        make \
        openssh-client \
        python2 \
        sed \ 
        tzdata \
        wget \
        which \
        zlib