version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock 
      - vscode-node_modules:/workspace/node_modules
      - vscode-next:/workspace/.next
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 3000:3000
  db:
    ports:
      - 3306:3306
volumes:
  vscode-node_modules:
  vscode-next: